/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AccountingService } from "../accounting.service";
import { AccountingCreateInput } from "./AccountingCreateInput";
import { Accounting } from "./Accounting";
import { AccountingFindManyArgs } from "./AccountingFindManyArgs";
import { AccountingWhereUniqueInput } from "./AccountingWhereUniqueInput";
import { AccountingUpdateInput } from "./AccountingUpdateInput";

export class AccountingControllerBase {
  constructor(protected readonly service: AccountingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Accounting })
  async createAccounting(
    @common.Body() data: AccountingCreateInput
  ): Promise<Accounting> {
    return await this.service.createAccounting({
      data: data,
      select: {
        amount: true,
        category: true,
        createdAt: true,
        description: true,
        entryDate: true,
        id: true,
        incomeOrExpense: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Accounting] })
  @ApiNestedQuery(AccountingFindManyArgs)
  async accountings(@common.Req() request: Request): Promise<Accounting[]> {
    const args = plainToClass(AccountingFindManyArgs, request.query);
    return this.service.accountings({
      ...args,
      select: {
        amount: true,
        category: true,
        createdAt: true,
        description: true,
        entryDate: true,
        id: true,
        incomeOrExpense: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Accounting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async accounting(
    @common.Param() params: AccountingWhereUniqueInput
  ): Promise<Accounting | null> {
    const result = await this.service.accounting({
      where: params,
      select: {
        amount: true,
        category: true,
        createdAt: true,
        description: true,
        entryDate: true,
        id: true,
        incomeOrExpense: true,
        updatedAt: true,
        user: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Accounting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAccounting(
    @common.Param() params: AccountingWhereUniqueInput,
    @common.Body() data: AccountingUpdateInput
  ): Promise<Accounting | null> {
    try {
      return await this.service.updateAccounting({
        where: params,
        data: data,
        select: {
          amount: true,
          category: true,
          createdAt: true,
          description: true,
          entryDate: true,
          id: true,
          incomeOrExpense: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Accounting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAccounting(
    @common.Param() params: AccountingWhereUniqueInput
  ): Promise<Accounting | null> {
    try {
      return await this.service.deleteAccounting({
        where: params,
        select: {
          amount: true,
          category: true,
          createdAt: true,
          description: true,
          entryDate: true,
          id: true,
          incomeOrExpense: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
